//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp.Modules
{
	public class Parameter : IParameter
	{
		float InitialValueRange = 10f;

		public float Value {
			get;
			set;
		}

		public float MutationChance {
			get;
			set;
		}

		public float MutationAmount {
			get;
			set;
		}

		public Parameter ()
		{
			Value = Util.SignedRange (InitialValueRange);
			MutationChance = Util.SignedRange (InitialValueRange);
			MutationAmount = Util.SignedRange (InitialValueRange);
		}

		public void Mutate ()
		{
			if (Util.Rnd.NextDouble() < MutationChance)
				Value += (float)Util.Rnd.NextDouble() * 2 * MutationAmount - MutationAmount;
		}
	}
}

